// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NewRoomReq struct {
	Username             string   `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	GameCode             string   `protobuf:"bytes,2,opt,name=gameCode" json:"gameCode,omitempty"`
	RoomName             string   `protobuf:"bytes,3,opt,name=roomName" json:"roomName,omitempty"`
	Pwd                  string   `protobuf:"bytes,4,opt,name=pwd" json:"pwd,omitempty"`
	SiteNum              int32    `protobuf:"varint,5,opt,name=siteNum" json:"siteNum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewRoomReq) Reset()         { *m = NewRoomReq{} }
func (m *NewRoomReq) String() string { return proto.CompactTextString(m) }
func (*NewRoomReq) ProtoMessage()    {}
func (*NewRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_fdd7deb0ee645eee, []int{0}
}
func (m *NewRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRoomReq.Unmarshal(m, b)
}
func (m *NewRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRoomReq.Marshal(b, m, deterministic)
}
func (dst *NewRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRoomReq.Merge(dst, src)
}
func (m *NewRoomReq) XXX_Size() int {
	return xxx_messageInfo_NewRoomReq.Size(m)
}
func (m *NewRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_NewRoomReq proto.InternalMessageInfo

func (m *NewRoomReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *NewRoomReq) GetGameCode() string {
	if m != nil {
		return m.GameCode
	}
	return ""
}

func (m *NewRoomReq) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *NewRoomReq) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

func (m *NewRoomReq) GetSiteNum() int32 {
	if m != nil {
		return m.SiteNum
	}
	return 0
}

type NewRoomResp struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId" json:"roomId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewRoomResp) Reset()         { *m = NewRoomResp{} }
func (m *NewRoomResp) String() string { return proto.CompactTextString(m) }
func (*NewRoomResp) ProtoMessage()    {}
func (*NewRoomResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_fdd7deb0ee645eee, []int{1}
}
func (m *NewRoomResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewRoomResp.Unmarshal(m, b)
}
func (m *NewRoomResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewRoomResp.Marshal(b, m, deterministic)
}
func (dst *NewRoomResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewRoomResp.Merge(dst, src)
}
func (m *NewRoomResp) XXX_Size() int {
	return xxx_messageInfo_NewRoomResp.Size(m)
}
func (m *NewRoomResp) XXX_DiscardUnknown() {
	xxx_messageInfo_NewRoomResp.DiscardUnknown(m)
}

var xxx_messageInfo_NewRoomResp proto.InternalMessageInfo

func (m *NewRoomResp) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

type AddRoomReq struct {
	RoomId               string   `protobuf:"bytes,1,opt,name=roomId" json:"roomId,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Pwd                  string   `protobuf:"bytes,3,opt,name=pwd" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRoomReq) Reset()         { *m = AddRoomReq{} }
func (m *AddRoomReq) String() string { return proto.CompactTextString(m) }
func (*AddRoomReq) ProtoMessage()    {}
func (*AddRoomReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_fdd7deb0ee645eee, []int{2}
}
func (m *AddRoomReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRoomReq.Unmarshal(m, b)
}
func (m *AddRoomReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRoomReq.Marshal(b, m, deterministic)
}
func (dst *AddRoomReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRoomReq.Merge(dst, src)
}
func (m *AddRoomReq) XXX_Size() int {
	return xxx_messageInfo_AddRoomReq.Size(m)
}
func (m *AddRoomReq) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRoomReq.DiscardUnknown(m)
}

var xxx_messageInfo_AddRoomReq proto.InternalMessageInfo

func (m *AddRoomReq) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *AddRoomReq) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AddRoomReq) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type RoomNilResp struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomNilResp) Reset()         { *m = RoomNilResp{} }
func (m *RoomNilResp) String() string { return proto.CompactTextString(m) }
func (*RoomNilResp) ProtoMessage()    {}
func (*RoomNilResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_room_fdd7deb0ee645eee, []int{3}
}
func (m *RoomNilResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomNilResp.Unmarshal(m, b)
}
func (m *RoomNilResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomNilResp.Marshal(b, m, deterministic)
}
func (dst *RoomNilResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomNilResp.Merge(dst, src)
}
func (m *RoomNilResp) XXX_Size() int {
	return xxx_messageInfo_RoomNilResp.Size(m)
}
func (m *RoomNilResp) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomNilResp.DiscardUnknown(m)
}

var xxx_messageInfo_RoomNilResp proto.InternalMessageInfo

func init() {
	proto.RegisterType((*NewRoomReq)(nil), "proto.NewRoomReq")
	proto.RegisterType((*NewRoomResp)(nil), "proto.NewRoomResp")
	proto.RegisterType((*AddRoomReq)(nil), "proto.AddRoomReq")
	proto.RegisterType((*RoomNilResp)(nil), "proto.RoomNilResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LeisureRoomServiceClient is the client API for LeisureRoomService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LeisureRoomServiceClient interface {
	CreateRoom(ctx context.Context, in *NewRoomReq, opts ...grpc.CallOption) (*NewRoomResp, error)
	AddRoom(ctx context.Context, in *AddRoomReq, opts ...grpc.CallOption) (*RoomNilResp, error)
}

type leisureRoomServiceClient struct {
	cc *grpc.ClientConn
}

func NewLeisureRoomServiceClient(cc *grpc.ClientConn) LeisureRoomServiceClient {
	return &leisureRoomServiceClient{cc}
}

func (c *leisureRoomServiceClient) CreateRoom(ctx context.Context, in *NewRoomReq, opts ...grpc.CallOption) (*NewRoomResp, error) {
	out := new(NewRoomResp)
	err := c.cc.Invoke(ctx, "/proto.LeisureRoomService/CreateRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *leisureRoomServiceClient) AddRoom(ctx context.Context, in *AddRoomReq, opts ...grpc.CallOption) (*RoomNilResp, error) {
	out := new(RoomNilResp)
	err := c.cc.Invoke(ctx, "/proto.LeisureRoomService/AddRoom", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LeisureRoomServiceServer is the server API for LeisureRoomService service.
type LeisureRoomServiceServer interface {
	CreateRoom(context.Context, *NewRoomReq) (*NewRoomResp, error)
	AddRoom(context.Context, *AddRoomReq) (*RoomNilResp, error)
}

func RegisterLeisureRoomServiceServer(s *grpc.Server, srv LeisureRoomServiceServer) {
	s.RegisterService(&_LeisureRoomService_serviceDesc, srv)
}

func _LeisureRoomService_CreateRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeisureRoomServiceServer).CreateRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LeisureRoomService/CreateRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeisureRoomServiceServer).CreateRoom(ctx, req.(*NewRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _LeisureRoomService_AddRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LeisureRoomServiceServer).AddRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.LeisureRoomService/AddRoom",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LeisureRoomServiceServer).AddRoom(ctx, req.(*AddRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _LeisureRoomService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.LeisureRoomService",
	HandlerType: (*LeisureRoomServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRoom",
			Handler:    _LeisureRoomService_CreateRoom_Handler,
		},
		{
			MethodName: "AddRoom",
			Handler:    _LeisureRoomService_AddRoom_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "room.proto",
}

func init() { proto.RegisterFile("room.proto", fileDescriptor_room_fdd7deb0ee645eee) }

var fileDescriptor_room_fdd7deb0ee645eee = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0x03, 0x31,
	0x10, 0x86, 0xbb, 0x5d, 0xb7, 0xd5, 0x29, 0x82, 0xce, 0x41, 0x42, 0x4f, 0x25, 0x20, 0xf4, 0xd4,
	0x43, 0xc5, 0x07, 0x90, 0x9e, 0x04, 0xd9, 0x43, 0x7c, 0x82, 0xd5, 0x0c, 0xb2, 0x60, 0xcc, 0x9a,
	0xec, 0xda, 0xa3, 0x2f, 0xe0, 0x43, 0xcb, 0x64, 0x93, 0x54, 0x0b, 0x3d, 0xed, 0xfe, 0xff, 0x9f,
	0x99, 0xf9, 0x66, 0x00, 0x9c, 0xb5, 0x66, 0xd3, 0x39, 0xdb, 0x5b, 0xac, 0xc2, 0x47, 0xfe, 0x14,
	0x00, 0x35, 0xed, 0x95, 0xb5, 0x46, 0xd1, 0x27, 0x2e, 0xe1, 0x7c, 0xf0, 0xe4, 0x3e, 0x1a, 0x43,
	0xa2, 0x58, 0x15, 0xeb, 0x0b, 0x95, 0x35, 0x67, 0x6f, 0x8d, 0xa1, 0x9d, 0xd5, 0x24, 0xa6, 0x63,
	0x96, 0x34, 0x67, 0xdc, 0xbb, 0xe6, 0xba, 0x72, 0xcc, 0x92, 0xc6, 0x2b, 0x28, 0xbb, 0xbd, 0x16,
	0x67, 0xc1, 0xe6, 0x5f, 0x14, 0x30, 0xf7, 0x6d, 0x4f, 0xf5, 0x60, 0x44, 0xb5, 0x2a, 0xd6, 0x95,
	0x4a, 0x52, 0xde, 0xc2, 0x22, 0xd3, 0xf8, 0x0e, 0x6f, 0x60, 0xc6, 0x6d, 0x1e, 0x75, 0x84, 0x89,
	0x4a, 0x2a, 0x80, 0x07, 0xad, 0x13, 0xf4, 0x89, 0x57, 0xff, 0x96, 0x99, 0x1e, 0x2d, 0x13, 0xa1,
	0xca, 0x0c, 0x25, 0x2f, 0x61, 0xc1, 0x0d, 0xeb, 0xf6, 0x9d, 0x47, 0x6f, 0xbf, 0x01, 0x9f, 0xa8,
	0xf5, 0x83, 0x23, 0x76, 0x9f, 0xc9, 0x7d, 0xb5, 0xaf, 0x84, 0xf7, 0x00, 0x3b, 0x47, 0x4d, 0x1f,
	0x4c, 0xbc, 0x1e, 0x6f, 0xb9, 0x39, 0x1c, 0x70, 0x89, 0xc7, 0x96, 0xef, 0xe4, 0x04, 0xb7, 0x30,
	0x8f, 0xbc, 0xb9, 0xe6, 0xc0, 0x9f, 0x6b, 0xfe, 0x8c, 0x97, 0x93, 0x97, 0x59, 0x30, 0xef, 0x7e,
	0x03, 0x00, 0x00, 0xff, 0xff, 0x8e, 0x07, 0x7f, 0xd2, 0xb5, 0x01, 0x00, 0x00,
}
